<a href="https://colab.research.google.com/github/ilknxr/first-contributions/blob/main/model_haz%C4%B1rlanmas%C4%B1_ve_e%C4%9Fitimi_notebook_2_.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [217]:
import tensorflow as tf
import numpy as np 
import pandas as pd 
import matplotlib.pyplot as plt



In [218]:
train = pd.read_csv("data_train.csv")
test  = pd.read_csv("data_test.csv")
val = pd.read_csv("data_val.csv")


In [219]:
train.head()

Unnamed: 0                                      image_X_train  Label
0           0  [[200 200 189 ...   0   0   0]\n [200 200 193 ...      7
1           1  [[200 200 189 ...   0   0   0]\n [200 200 193 ...      8
2           2  [[200 200 189 ...   0   0   0]\n [200 200 193 ...      9
3           3  [[200 200 189 ...   0   0   0]\n [200 200 193 ...      0
4           4  [[200 200 189 ...   0   0   0]\n [200 200 193 ...      5

In [220]:
test.head()


Unnamed: 0                                      image_X_test   Label
0           0  [[200 200 189 ...   0   0   0]\n [200 200 193 ...      2
1           1  [[200 200 189 ...   0   0   0]\n [200 200 193 ...      3
2           2  [[200 200 189 ...   0   0   0]\n [200 200 193 ...      8
3           3  [[200 200 189 ...   0   0   0]\n [200 200 193 ...      5
4           4  [[200 200 189 ...   0   0   0]\n [200 200 193 ...      7

In [221]:
val.head()

Unnamed: 0                                        image_X_val  Label
0           0  [[200 200 189 ...   0   0   0]\n [200 200 193 ...      5
1           1  [[200 200 189 ...   0   0   0]\n [200 200 193 ...      2
2           2  [[200 200 189 ...   0   0   0]\n [200 200 193 ...      9
3           3  [[200 200 189 ...   0   0   0]\n [200 200 193 ...      0
4           4  [[200 200 189 ...   0   0   0]\n [200 200 193 ...      4

In [235]:
print(type(train["image_X_train"][1]))

<class 'str'>


In [222]:
#image_X_train, image_X_test ve image_X_val kolonları "array" formatında olmasına rağmen anlam veremediğimiz bir şekilde "string" formatında döndürdü.
#Dolayısıyla modeli eğitirken sorun yaşadık. 

In [223]:
x_train = train.iloc[:, 1:].values

y_train = train.iloc[:, 2:].values

x_test = test.iloc[:, 1:].values

y_test = test.iloc[:, 2:].values

x_val = val.iloc[:, 1:].values

y_val = val.iloc[:, 2:].values



In [224]:
print(x_train)
print(f"x_train: {len(x_train)}")

[['[[200 200 189 ...   0   0   0]\n [200 200 193 ...   0   0   0]\n [200 200 194 ...   0   0   0]\n ...\n [200 200 191 ...  75  75  75]\n [200 200 200 ... 198 198 198]\n [200 200 200 ... 200 200 200]]'
  7]
 ['[[200 200 189 ...   0   0   0]\n [200 200 193 ...   0   0   0]\n [200 200 194 ...   0   0   0]\n ...\n [200 200 191 ...  75  75  75]\n [200 200 200 ... 198 198 198]\n [200 200 200 ... 200 200 200]]'
  8]
 ['[[200 200 189 ...   0   0   0]\n [200 200 193 ...   0   0   0]\n [200 200 194 ...   0   0   0]\n ...\n [200 200 191 ...  75  75  75]\n [200 200 200 ... 198 198 198]\n [200 200 200 ... 200 200 200]]'
  9]
 ...
 ['[[200 200 189 ...   0   0   0]\n [200 200 193 ...   0   0   0]\n [200 200 194 ...   0   0   0]\n ...\n [200 200 191 ...  75  75  75]\n [200 200 200 ... 198 198 198]\n [200 200 200 ... 200 200 200]]'
  7]
 ['[[200 200 189 ...   0   0   0]\n [200 200 193 ...   0   0   0]\n [200 200 194 ...   0   0   0]\n ...\n [200 200 191 ...  76  76  75]\n [200 200 200 ... 198 198 198]

In [225]:
print(y_train)
print(f"y_train: {len(y_train)}")


[[7]
 [8]
 [9]
 ...
 [7]
 [5]
 [3]]
y_train: 5238


In [226]:
print(x_test)
print(f"x_test: {len(x_test)}")

[['[[200 200 189 ...   0   0   0]\n [200 200 193 ...   0   0   0]\n [200 200 194 ...   0   0   0]\n ...\n [200 200 191 ...  75  75  75]\n [200 200 200 ... 198 198 198]\n [200 200 200 ... 200 200 200]]'
  2]
 ['[[200 200 189 ...   0   0   0]\n [200 200 193 ...   0   0   0]\n [200 200 194 ...   0   0   0]\n ...\n [200 200 191 ...  75  75  75]\n [200 200 200 ... 198 198 198]\n [200 200 200 ... 200 200 200]]'
  3]
 ['[[200 200 189 ...   0   0   0]\n [200 200 193 ...   0   0   0]\n [200 200 194 ...   0   0   0]\n ...\n [200 200 191 ...  75  75  75]\n [200 200 200 ... 198 198 198]\n [200 200 200 ... 200 200 200]]'
  8]
 ...
 ['[[200 200 189 ...   0   0   0]\n [200 200 193 ...   0   0   0]\n [200 200 194 ...   0   0   0]\n ...\n [200 200 191 ...  75  75  75]\n [200 200 200 ... 198 198 198]\n [200 200 200 ... 200 200 200]]'
  4]
 ['[[200 200 189 ...   0   0   0]\n [200 200 193 ...   0   0   0]\n [200 200 194 ...   0   0   0]\n ...\n [200 200 191 ...  75  75  75]\n [200 200 200 ... 198 198 198]

In [227]:
print(y_test)
print(f"y_test: {len(y_test)}")

[[2]
 [3]
 [8]
 ...
 [4]
 [7]
 [4]]
y_test: 1747


In [228]:
print(x_val)
print(f"x_val: {len(x_val)}")

[['[[200 200 189 ...   0   0   0]\n [200 200 193 ...   0   0   0]\n [200 200 194 ...   0   0   0]\n ...\n [200 200 191 ...  75  75  75]\n [200 200 200 ... 198 198 198]\n [200 200 200 ... 200 200 200]]'
  5]
 ['[[200 200 189 ...   0   0   0]\n [200 200 193 ...   0   0   0]\n [200 200 194 ...   0   0   0]\n ...\n [200 200 191 ...  75  75  75]\n [200 200 200 ... 198 198 198]\n [200 200 200 ... 200 200 200]]'
  2]
 ['[[200 200 189 ...   0   0   0]\n [200 200 193 ...   0   0   0]\n [200 200 194 ...   0   0   0]\n ...\n [200 200 191 ...  75  75  75]\n [200 200 200 ... 198 198 198]\n [200 200 200 ... 200 200 200]]'
  9]
 ...
 ['[[200 200 189 ...   0   0   0]\n [200 200 193 ...   0   0   0]\n [200 200 194 ...   0   0   0]\n ...\n [200 200 191 ...  75  75  75]\n [200 200 200 ... 198 198 198]\n [200 200 200 ... 200 200 200]]'
  8]
 ['[[200 200 189 ...   0   0   0]\n [200 200 193 ...   0   0   0]\n [200 200 194 ...   0   0   0]\n ...\n [200 200 191 ...  75  75  75]\n [200 200 200 ... 198 198 198]

In [229]:
print(y_val)
print(f"y_val: {len(y_val)}")

[[5]
 [2]
 [9]
 ...
 [8]
 [0]
 [0]]
y_val: 1747


In [230]:
x_train.shape,x_test.shape,y_train.shape,y_test.shape


((5238, 2), (1747, 2), (5238, 1), (1747, 1))

In [231]:
import cv2
img = cv2.imread("/content/drive/MyDrive/spectrograms/0/100852-0-0-0.png")
print(img.shape)

(374, 500, 3)


In [232]:
from keras import Sequential
from keras.layers import Dense,Conv2D,MaxPooling2D,Flatten,Dropout

model = tf.keras.Sequential()
model.add(Conv2D(64,kernel_size=(3,3),strides=(1,1),padding="Same",activation="relu",input_shape=(374,500,3)))
model.add(MaxPooling2D(padding="same"))

model.add(Conv2D(128,kernel_size=(3,3),strides=(1,1),padding="same",activation="relu"))
model.add(MaxPooling2D(padding="same"))
model.add(Dropout(0.5))

model.add(Flatten())

model.add(Dense(256,activation="relu"))
model.add(Dropout(0.5))

model.add(Dense(512,activation="relu"))
model.add(Dropout(0.5))

model.add(Dense(10,activation="softmax"))


model.compile(optimizer="adam",loss="categorical_crossentropy",metrics=["accuracy"])



In [233]:
results = model.fit(x_train,y_train,batch_size=90,epochs=45,validation_data=(x_val,y_val))


ValueError: ignored

In [ ]:
#Başta belirttiğimiz hata sebebiyle modeli fitlemede de problem yaşadık. 
#Nasıl düzelteceğimizi bilmediğimiz için ve çalışmamış olmamak için de eğer hata almasak nasıl devam ederdik onun kodlarını yazdık.

In [ ]:
plt.plot(results.history["loss"], label="loss")

plt.plot(results.history["val_loss"], label="val_loss")


plt.xlabel("Epochs")
plt.ylabel("Loss")

plt.legend()

plt.show()

In [ ]:
model.evaluate(x_test,y_test)

In [ ]:
prediction_result = model.predict(x_test[7].reshape(374,500,3))

prediction_result

In [ ]:
predicted_class =prediction_result.argmax()

predicted_probability=prediction_result.max()

print(predicted_class)
print(predicted_probability)

In [ ]:
#Modelimizin çalışmadığını biliyoruz fakat baştaki sorunu çözemediğimiz için ilerleyemedik.